name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Permissions & Setup Directory
        run: |
          sudo chmod -R 777 .
          mkdir -p .buildozer

      - name: Build APK with Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/hostpython \
            -w /home/user/hostpython \
            -e BUILDOZER_ACCEPT_SDK_LICENSES=1 \
            kivy/buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OSCAN-APK
          path: bin/*.apk
