name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fix Directory Permissions
        run: |
          chmod -R 777 .

      - name: Build APK using Official Buildozer Docker Container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/hostpython \
            -e BUILDOZER_WARN_ON_ROOT=0 \
            kivy/buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OSCAN-APK
          path: bin/*.apk
